#!/usr/bin/awk

BEGIN {
   cnt = 0;
   sum = 0;
   i   = 0;
   printf "%15s %12s %6s %12s %12s\n", "Time", "Total", "Count", "Avg", "1-Min Avg";
}
/^# Time: / {
   sums[i] = sum;
   cnts[i] = cnt;
   cnt60 = 0;
   sum60 = 0;
   for (j in cnts) {
      cnt60 += cnts[j];
      sum60 += sums[j];
   }
   if ( cnt > 0 ) {
      avg = sum / cnt;
   }
   else {
      cur = 0;
   }
   if ( cnt60 > 0 ) {
      avg60 = sum60 / cnt60;
   }
   else {
      avg60 = 0;
   }
   printf "%6s %8s %12.6f %6d %12.6f %12.6f\n", $3, $4, sum, cnt, avg, avg60;
   i++;
   if ( i >= 60 ) {
      i = 0;
   }
   cnt = 0;
   sum = 0;
}
/^# Query_time/ {
   cnt++;
   sum += $3;
}
