#!/bin/bash
#format_open_tables

cat <<EOF > $1
  Top open tables                          CNT
  ---------------------------------------- ---
  sakila.film                                1
  sakila.actor                               1
  sakila.store                               0
  sakila.staff                               0
  sakila.rental                              0
EOF

cp samples/mysql-show-open-tables-001.txt $2
