#!/bin/bash
#format_overall_db_stats

cat <<EOF > $1

  Database Tables Views SPs Trigs Funcs   FKs Partn
  mysql        17                                  
  sakila       17     7   3     6     3    22     1

  Database MyISAM InnoDB
  mysql        17       
  sakila        2     15

  Database BTREE FULLTEXT
  mysql       24         
  sakila      63        1

  Database char timestamp set enum tinyint smallint int text blob longblob bigint varchar datetime year decimal mediumint
  mysql      38         5   5   69       2        3  16    2    4        1      2                                        
  sakila      1        15   1    3      19       26   3    4    1                      45        4    1       7         2

EOF

cp samples/mysql-schema-001.txt /tmp/aspersa-mysqldump
